select 
B.CLAVE,B.NOMBRE
,A.VENDEDOR,A.PLAZO,A.LIMITE
,NVL(MAX(ROUND((SELECT (TO_DATE('14/02/2008','DD/MM/YYYY')-X.VENCIMIENTO)-7 FROM SW_VENTASCREDITO X WHERE X.VENTA_ID=B.VENTA_ID AND X.VENCIMIENTO<(TO_DATE('14/02/2008','DD/MM/YYYY'))
     AND ((B.TOTAL)-
     NVL((SELECT SUM(X.IMPORTE) FROM SW_PAGOS X  WHERE X.VENTA_ID=B.VENTA_ID AND X.YEAR>=2007 AND X.FECHA<=(TO_DATE('14/02/2008','DD/MM/YYYY')-7) AND X.FORMADEPAGO<>'U'),0) +
     NVL((SELECT SUM(X.IMPORTE) FROM SW_NOTASDET X  WHERE X.VENTA_ID=B.VENTA_ID AND  X.YEAR>=2007 AND X.SERIE<>'M' AND X.FECHA<=(TO_DATE('14/02/2008','DD/MM/YYYY')-7) AND X.ORIGEN='CRE' 
     AND NOTA_ID IN(SELECT Y.NOTA_ID FROM SW_NOTAS Y WHERE Y.APLICABLE=0 AND X.NOTA_ID=Y.NOTA_ID)),0))>0),0)),0) AS ATR_SEM_P
,SUM(NVL((SELECT SUM(X.IMPORTE) FROM SW_PAGOS X  WHERE X.VENTA_ID=B.VENTA_ID AND X.YEAR>=2007 AND X.FECHA BETWEEN TO_DATE('14/02/2008','DD/MM/YYYY')-13 AND TO_DATE('14/02/2008','DD/MM/YYYY')-7 AND X.FORMADEPAGO<>'U'),0)) AS PAG_SEM_P
,NVL(MAX(ROUND((SELECT (TO_DATE('14/02/2008','DD/MM/YYYY')-X.VENCIMIENTO) FROM SW_VENTASCREDITO X WHERE X.VENTA_ID=B.VENTA_ID AND X.VENCIMIENTO<'14/02/2008'   
   AND ((B.TOTAL)-
   NVL((SELECT SUM(X.IMPORTE) FROM SW_PAGOS X  WHERE X.VENTA_ID=B.VENTA_ID AND X.YEAR>=2007 AND X.FECHA<='14/02/2008' AND X.FORMADEPAGO<>'U'),0) +
   NVL((SELECT SUM(X.IMPORTE) FROM SW_NOTASDET X  WHERE X.VENTA_ID=B.VENTA_ID AND  X.YEAR>=2007 AND X.SERIE<>'M' AND X.FECHA<='14/02/2008' AND X.ORIGEN='CRE' 
   AND NOTA_ID IN(SELECT Y.NOTA_ID FROM SW_NOTAS Y WHERE Y.APLICABLE=0 AND X.NOTA_ID=Y.NOTA_ID)),0))>0),0)),0) AS ATRASO_MAX
,SUM(NVL((SELECT SUM(X.IMPORTE) FROM SW_PAGOS X  WHERE X.VENTA_ID=B.VENTA_ID AND X.YEAR>=2007 AND X.FECHA BETWEEN TO_DATE('14/02/2008','DD/MM/YYYY')-6 AND TO_DATE('14/02/2008','DD/MM/YYYY') AND X.FORMADEPAGO<>'U'),0)) AS PAG_SEM_A
,MAX((SELECT MAX(X.FECHA) FROM SW_VENTAS X  WHERE X.VENTA_ID=B.VENTA_ID AND X.YEAR>=2007 AND X.FECHA<='14/02/2008')) AS ULT_VENTA
,MAX((SELECT MAX(X.FECHA) FROM SW_PAGOS X  WHERE X.VENTA_ID=B.VENTA_ID AND X.YEAR>=2007 AND X.FECHA<='14/02/2008')) AS ULT_PAGO
,SUM(B.TOTAL)-
   NVL(SUM((SELECT SUM(X.IMPORTE) FROM SW_PAGOS X  WHERE X.VENTA_ID=B.VENTA_ID AND X.YEAR>=2007 AND X.FECHA<='14/02/2008' AND X.FORMADEPAGO<>'U')),0) +
   NVL(SUM((SELECT SUM(X.IMPORTE) FROM SW_NOTASDET X  WHERE X.VENTA_ID=B.VENTA_ID AND  X.YEAR>=2007 AND X.SERIE<>'M' AND X.FECHA<='14/02/2008' AND X.ORIGEN='CRE' 
    AND NOTA_ID IN(SELECT Y.NOTA_ID FROM SW_NOTAS Y WHERE Y.APLICABLE=0 AND X.NOTA_ID=Y.NOTA_ID))),0)AS SALD_XXX
,SUM(CASE WHEN
   NVL((ROUND((SELECT (TO_DATE('14/02/2008','DD/MM/YYYY')-X.VENCIMIENTO) FROM SW_VENTASCREDITO X WHERE X.VENTA_ID=B.VENTA_ID AND X.VENCIMIENTO<'14/02/2008'   
     AND ((B.TOTAL)-
     NVL((SELECT SUM(X.IMPORTE) FROM SW_PAGOS X  WHERE X.VENTA_ID=B.VENTA_ID AND X.YEAR>=2007 AND X.FECHA<='14/02/2008' AND X.FORMADEPAGO<>'U'),0) +
     NVL((SELECT SUM(X.IMPORTE) FROM SW_NOTASDET X  WHERE X.VENTA_ID=B.VENTA_ID AND  X.YEAR>=2007 AND X.SERIE<>'M' AND X.FECHA<='14/02/2008' AND X.ORIGEN='CRE' 
     AND NOTA_ID IN(SELECT Y.NOTA_ID FROM SW_NOTAS Y WHERE Y.APLICABLE=0 AND X.NOTA_ID=Y.NOTA_ID)),0))>0),0)),0)>7 THEN
  (B.TOTAL)-
     NVL(((SELECT SUM(X.IMPORTE) FROM SW_PAGOS X  WHERE X.VENTA_ID=B.VENTA_ID AND X.YEAR>=2007 AND X.FECHA<='14/02/2008' AND X.FORMADEPAGO<>'U')),0) +
     NVL(((SELECT SUM(X.IMPORTE) FROM SW_NOTASDET X  WHERE X.VENTA_ID=B.VENTA_ID AND  X.YEAR>=2007 AND X.SERIE<>'M' AND X.FECHA<='14/02/2008' AND X.ORIGEN='CRE' 
     AND NOTA_ID IN(SELECT Y.NOTA_ID FROM SW_NOTAS Y WHERE Y.APLICABLE=0 AND X.NOTA_ID=Y.NOTA_ID))),0) 
ELSE 0 END) AS SALDO_VENC
,COUNT((SELECT X.NUMERO FROM V_VENTAS X WHERE X.VENTA_ID=B.VENTA_ID AND X.VENCIMIENTO<='14/02/2008'
AND 
NVL((ROUND((SELECT (TO_DATE('14/02/2008','DD/MM/YYYY')-X.VENCIMIENTO) FROM SW_VENTASCREDITO X WHERE X.VENTA_ID=B.VENTA_ID AND X.VENCIMIENTO<'14/02/2008'
     AND ((B.TOTAL)-
     NVL((SELECT SUM(X.IMPORTE) FROM SW_PAGOS X  WHERE X.VENTA_ID=B.VENTA_ID AND X.YEAR>=2007 AND X.FECHA<='14/02/2008' AND X.FORMADEPAGO<>'U'),0) +
     NVL((SELECT SUM(X.IMPORTE) FROM SW_NOTASDET X  WHERE X.VENTA_ID=B.VENTA_ID AND  X.YEAR>=2007 AND X.SERIE<>'M' AND X.FECHA<='14/02/2008' AND X.ORIGEN='CRE' 
     AND NOTA_ID IN(SELECT Y.NOTA_ID FROM SW_NOTAS Y WHERE Y.APLICABLE=0 AND X.NOTA_ID=Y.NOTA_ID)),0))>0),0)),0)>7 
)) AS FACTS_VENC,A.COMENTARIOCXC
,CASE WHEN 
         ( NVL(MAX(ROUND((SELECT (TO_DATE('14/02/2008','DD/MM/YYYY')-X.VENCIMIENTO)-7 FROM SW_VENTASCREDITO X WHERE X.VENTA_ID=B.VENTA_ID AND X.VENCIMIENTO<(TO_DATE('14/02/2008','DD/MM/YYYY'))
            AND ((B.TOTAL)-
            NVL((SELECT SUM(X.IMPORTE) FROM SW_PAGOS X  WHERE X.VENTA_ID=B.VENTA_ID AND X.YEAR>=2007 AND X.FECHA<=(TO_DATE('14/02/2008','DD/MM/YYYY')-7) AND X.FORMADEPAGO<>'U'),0) +
            NVL((SELECT SUM(X.IMPORTE) FROM SW_NOTASDET X  WHERE X.VENTA_ID=B.VENTA_ID AND  X.YEAR>=2007 AND X.SERIE<>'M' AND X.FECHA<=(TO_DATE('14/02/2008','DD/MM/YYYY')-7) AND X.ORIGEN='CRE' 
            AND NOTA_ID IN(SELECT Y.NOTA_ID FROM SW_NOTAS Y WHERE Y.APLICABLE=0 AND X.NOTA_ID=Y.NOTA_ID)),0))>0),0)),0) --AS ATR_SEM_P
        + SUM(NVL((SELECT SUM(X.IMPORTE) FROM SW_PAGOS X  WHERE X.VENTA_ID=B.VENTA_ID AND X.YEAR>=2007 AND X.FECHA BETWEEN TO_DATE('14/02/2008','DD/MM/YYYY')-13 AND TO_DATE('14/02/2008','DD/MM/YYYY')-7 AND X.FORMADEPAGO<>'U'),0)) --AS PAG_SEM_P
        + NVL(MAX(ROUND((SELECT (TO_DATE('14/02/2008','DD/MM/YYYY')-X.VENCIMIENTO) FROM SW_VENTASCREDITO X WHERE X.VENTA_ID=B.VENTA_ID AND X.VENCIMIENTO<'14/02/2008'   
            AND ((B.TOTAL)-
            NVL((SELECT SUM(X.IMPORTE) FROM SW_PAGOS X  WHERE X.VENTA_ID=B.VENTA_ID AND X.YEAR>=2007 AND X.FECHA<='14/02/2008' AND X.FORMADEPAGO<>'U'),0) +
            NVL((SELECT SUM(X.IMPORTE) FROM SW_NOTASDET X  WHERE X.VENTA_ID=B.VENTA_ID AND  X.YEAR>=2007 AND X.SERIE<>'M' AND X.FECHA<='14/02/2008' AND X.ORIGEN='CRE' 
            AND NOTA_ID IN(SELECT Y.NOTA_ID FROM SW_NOTAS Y WHERE Y.APLICABLE=0 AND X.NOTA_ID=Y.NOTA_ID)),0))>0),0)),0) --AS ATRASO_MAX
        + SUM(NVL((SELECT SUM(X.IMPORTE) FROM SW_PAGOS X  WHERE X.VENTA_ID=B.VENTA_ID AND X.YEAR>=2007 AND X.FECHA BETWEEN TO_DATE('14/02/2008','DD/MM/YYYY')-6 AND TO_DATE('14/02/2008','DD/MM/YYYY') AND X.FORMADEPAGO<>'U'),0)) --AS PAG_SEM_A
        + SUM(B.TOTAL)-
            NVL(SUM((SELECT SUM(X.IMPORTE) FROM SW_PAGOS X  WHERE X.VENTA_ID=B.VENTA_ID AND X.YEAR>=2007 AND X.FECHA<='14/02/2008' AND X.FORMADEPAGO<>'U')),0) +
            NVL(SUM((SELECT SUM(X.IMPORTE) FROM SW_NOTASDET X  WHERE X.VENTA_ID=B.VENTA_ID AND  X.YEAR>=2007 AND X.SERIE<>'M' AND X.FECHA<='14/02/2008' AND X.ORIGEN='CRE' 
            AND NOTA_ID IN(SELECT Y.NOTA_ID FROM SW_NOTAS Y WHERE Y.APLICABLE=0 AND X.NOTA_ID=Y.NOTA_ID))),0)) --AS SALD_XXX
        = 0 THEN 'NoCompra'  ELSE 
CASE WHEN --2
         SUM((NVL((SELECT SUM(X.IMPORTE) FROM SW_PAGOS X  WHERE X.VENTA_ID=B.VENTA_ID AND X.YEAR>=2007 AND X.FECHA BETWEEN TO_DATE('14/02/2008','DD/MM/YYYY')-6 AND TO_DATE('14/02/2008','DD/MM/YYYY') AND X.FORMADEPAGO<>'U'),0)) --AS PAG_SEM_A
       + ((B.TOTAL)-
            NVL(((SELECT SUM(X.IMPORTE) FROM SW_PAGOS X  WHERE X.VENTA_ID=B.VENTA_ID AND X.YEAR>=2007 AND X.FECHA<='14/02/2008' AND X.FORMADEPAGO<>'U')),0) +
            NVL(((SELECT SUM(X.IMPORTE) FROM SW_NOTASDET X  WHERE X.VENTA_ID=B.VENTA_ID AND  X.YEAR>=2007 AND X.SERIE<>'M' AND X.FECHA<='14/02/2008' AND X.ORIGEN='CRE' 
            AND NOTA_ID IN(SELECT Y.NOTA_ID FROM SW_NOTAS Y WHERE Y.APLICABLE=0 AND X.NOTA_ID=Y.NOTA_ID))),0))) --AS SALDO_VENC
       = 0 THEN 'SinMov' ELSE 
CASE WHEN --3
         SUM(NVL((SELECT SUM(X.IMPORTE) FROM SW_PAGOS X  WHERE X.VENTA_ID=B.VENTA_ID AND X.YEAR>=2007 AND X.FECHA BETWEEN TO_DATE('14/02/2008','DD/MM/YYYY')-6 AND TO_DATE('14/02/2008','DD/MM/YYYY') AND X.FORMADEPAGO<>'U'),0)) --AS PAG_SEM_A
       <=1 THEN 'NoAbono' ELSE 
                'CON_PAGOS' END END END AS STATUS
,CASE WHEN  
        LIMITE-(SUM(B.TOTAL)-
        NVL(SUM((SELECT SUM(X.IMPORTE) FROM SW_PAGOS X  WHERE X.VENTA_ID=B.VENTA_ID AND X.YEAR>=2007 AND X.FECHA<='14/02/2008' AND X.FORMADEPAGO<>'U')),0) +
        NVL(SUM((SELECT SUM(X.IMPORTE) FROM SW_NOTASDET X  WHERE X.VENTA_ID=B.VENTA_ID AND  X.YEAR>=2007 AND X.SERIE<>'M' AND X.FECHA<='14/02/2008' AND X.ORIGEN='CRE' 
        AND NOTA_ID IN(SELECT Y.NOTA_ID FROM SW_NOTAS Y WHERE Y.APLICABLE=0 AND X.NOTA_ID=Y.NOTA_ID))),0))<0 THEN 'Excedido' ELSE  --AS SALD_XXX
CASE WHEN 
         SUM((NVL((SELECT SUM(X.IMPORTE) FROM SW_PAGOS X  WHERE X.VENTA_ID=B.VENTA_ID AND X.YEAR>=2007 AND X.FECHA BETWEEN TO_DATE('14/02/2008','DD/MM/YYYY')-6 AND TO_DATE('14/02/2008','DD/MM/YYYY') AND X.FORMADEPAGO<>'U'),0))) --AS PAG_SEM_A
        + (NVL(MAX(ROUND((SELECT (TO_DATE('14/02/2008','DD/MM/YYYY')-X.VENCIMIENTO) FROM SW_VENTASCREDITO X WHERE X.VENTA_ID=B.VENTA_ID AND X.VENCIMIENTO<'14/02/2008'   
            AND ((B.TOTAL)-
            NVL((SELECT SUM(X.IMPORTE) FROM SW_PAGOS X  WHERE X.VENTA_ID=B.VENTA_ID AND X.YEAR>=2007 AND X.FECHA<='14/02/2008' AND X.FORMADEPAGO<>'U'),0) +
            NVL((SELECT SUM(X.IMPORTE) FROM SW_NOTASDET X  WHERE X.VENTA_ID=B.VENTA_ID AND  X.YEAR>=2007 AND X.SERIE<>'M' AND X.FECHA<='14/02/2008' AND X.ORIGEN='CRE' 
            AND NOTA_ID IN(SELECT Y.NOTA_ID FROM SW_NOTAS Y WHERE Y.APLICABLE=0 AND X.NOTA_ID=Y.NOTA_ID)),0))>0),0)),0))        
       + SUM((B.TOTAL)-
            NVL(((SELECT SUM(X.IMPORTE) FROM SW_PAGOS X  WHERE X.VENTA_ID=B.VENTA_ID AND X.YEAR>=2007 AND X.FECHA<='14/02/2008' AND X.FORMADEPAGO<>'U')),0) +
            NVL(((SELECT SUM(X.IMPORTE) FROM SW_NOTASDET X  WHERE X.VENTA_ID=B.VENTA_ID AND  X.YEAR>=2007 AND X.SERIE<>'M' AND X.FECHA<='14/02/2008' AND X.ORIGEN='CRE' 
            AND NOTA_ID IN(SELECT Y.NOTA_ID FROM SW_NOTAS Y WHERE Y.APLICABLE=0 AND X.NOTA_ID=Y.NOTA_ID))),0)) 
       = 0 THEN 'Estable' ELSE 
CASE WHEN 
(NVL(MAX(ROUND((SELECT (TO_DATE('14/02/2008','DD/MM/YYYY')-X.VENCIMIENTO) FROM SW_VENTASCREDITO X WHERE X.VENTA_ID=B.VENTA_ID AND X.VENCIMIENTO<'14/02/2008'   
            AND ((B.TOTAL)-
            NVL((SELECT SUM(X.IMPORTE) FROM SW_PAGOS X  WHERE X.VENTA_ID=B.VENTA_ID AND X.YEAR>=2007 AND X.FECHA<='14/02/2008' AND X.FORMADEPAGO<>'U'),0) +
            NVL((SELECT SUM(X.IMPORTE) FROM SW_NOTASDET X  WHERE X.VENTA_ID=B.VENTA_ID AND  X.YEAR>=2007 AND X.SERIE<>'M' AND X.FECHA<='14/02/2008' AND X.ORIGEN='CRE' 
            AND NOTA_ID IN(SELECT Y.NOTA_ID FROM SW_NOTAS Y WHERE Y.APLICABLE=0 AND X.NOTA_ID=Y.NOTA_ID)),0))>0),0)),0)) 
       <8 THEN 'PorVencer' ELSE 
CASE WHEN 
(NVL(MAX(ROUND((SELECT (TO_DATE('14/02/2008','DD/MM/YYYY')-X.VENCIMIENTO) FROM SW_VENTASCREDITO X WHERE X.VENTA_ID=B.VENTA_ID AND X.VENCIMIENTO<'14/02/2008'   
            AND ((B.TOTAL)-
            NVL((SELECT SUM(X.IMPORTE) FROM SW_PAGOS X  WHERE X.VENTA_ID=B.VENTA_ID AND X.YEAR>=2007 AND X.FECHA<='14/02/2008' AND X.FORMADEPAGO<>'U'),0) +
            NVL((SELECT SUM(X.IMPORTE) FROM SW_NOTASDET X  WHERE X.VENTA_ID=B.VENTA_ID AND  X.YEAR>=2007 AND X.SERIE<>'M' AND X.FECHA<='14/02/2008' AND X.ORIGEN='CRE' 
            AND NOTA_ID IN(SELECT Y.NOTA_ID FROM SW_NOTAS Y WHERE Y.APLICABLE=0 AND X.NOTA_ID=Y.NOTA_ID)),0))>0),0)),0)) 
       <20 THEN 'Alerta' ELSE 
CASE WHEN 
          SUM((B.TOTAL)-
            NVL(((SELECT SUM(X.IMPORTE) FROM SW_PAGOS X  WHERE X.VENTA_ID=B.VENTA_ID AND X.YEAR>=2007 AND X.FECHA<='14/02/2008' AND X.FORMADEPAGO<>'U')),0) +
            NVL(((SELECT SUM(X.IMPORTE) FROM SW_NOTASDET X  WHERE X.VENTA_ID=B.VENTA_ID AND  X.YEAR>=2007 AND X.SERIE<>'M' AND X.FECHA<='14/02/2008' AND X.ORIGEN='CRE' 
            AND NOTA_ID IN(SELECT Y.NOTA_ID FROM SW_NOTAS Y WHERE Y.APLICABLE=0 AND X.NOTA_ID=Y.NOTA_ID))),0))*100/A.LIMITE 
       >40  THEN 'Suspender'  ELSE
CASE WHEN 
(NVL(MAX(ROUND((SELECT (TO_DATE('14/02/2008','DD/MM/YYYY')-X.VENCIMIENTO) FROM SW_VENTASCREDITO X WHERE X.VENTA_ID=B.VENTA_ID AND X.VENCIMIENTO<'14/02/2008'   
            AND ((B.TOTAL)-
            NVL((SELECT SUM(X.IMPORTE) FROM SW_PAGOS X  WHERE X.VENTA_ID=B.VENTA_ID AND X.YEAR>=2007 AND X.FECHA<='14/02/2008' AND X.FORMADEPAGO<>'U'),0) +
            NVL((SELECT SUM(X.IMPORTE) FROM SW_NOTASDET X  WHERE X.VENTA_ID=B.VENTA_ID AND  X.YEAR>=2007 AND X.SERIE<>'M' AND X.FECHA<='14/02/2008' AND X.ORIGEN='CRE' 
            AND NOTA_ID IN(SELECT Y.NOTA_ID FROM SW_NOTAS Y WHERE Y.APLICABLE=0 AND X.NOTA_ID=Y.NOTA_ID)),0))>0),0)),0))
       <60 THEN 'SuspxAtr' ELSE 'Juridico'
END END END END END END AS AVISO,
ROUND(
        CASE WHEN  SUM(NVL((SELECT SUM(X.IMPORTE) FROM SW_PAGOS X  WHERE X.VENTA_ID=B.VENTA_ID AND X.YEAR>=2007 AND X.FECHA BETWEEN TO_DATE('14/02/2008','DD/MM/YYYY')-6 AND TO_DATE('14/02/2008','DD/MM/YYYY') AND X.FORMADEPAGO<>'U'),0))=0  THEN 0 ELSE --100 END --AS PAG_SEM_A
        SUM(NVL((SELECT SUM(X.IMPORTE) FROM SW_PAGOS X  WHERE X.VENTA_ID=B.VENTA_ID AND X.YEAR>=2007 AND X.FECHA BETWEEN TO_DATE('14/02/2008','DD/MM/YYYY')-6 AND TO_DATE('14/02/2008','DD/MM/YYYY') AND X.FORMADEPAGO<>'U'),0))*100/ --AS PAG_SEM_A
        (SUM(NVL((SELECT SUM(X.IMPORTE) FROM SW_PAGOS X  WHERE X.VENTA_ID=B.VENTA_ID AND X.YEAR>=2007 AND X.FECHA BETWEEN TO_DATE('14/02/2008','DD/MM/YYYY')-6 AND TO_DATE('14/02/2008','DD/MM/YYYY') AND X.FORMADEPAGO<>'U'),0)) --END --AS PAG_SEM_A
       + 
        SUM(CASE WHEN
         NVL((ROUND((SELECT (TO_DATE('14/02/2008','DD/MM/YYYY')-X.VENCIMIENTO) FROM SW_VENTASCREDITO X WHERE X.VENTA_ID=B.VENTA_ID AND X.VENCIMIENTO<'14/02/2008'   
         AND ((B.TOTAL)-
         NVL((SELECT SUM(X.IMPORTE) FROM SW_PAGOS X  WHERE X.VENTA_ID=B.VENTA_ID AND X.YEAR>=2007 AND X.FECHA<='14/02/2008' AND X.FORMADEPAGO<>'U'),0) +
         NVL((SELECT SUM(X.IMPORTE) FROM SW_NOTASDET X  WHERE X.VENTA_ID=B.VENTA_ID AND  X.YEAR>=2007 AND X.SERIE<>'M' AND X.FECHA<='14/02/2008' AND X.ORIGEN='CRE' 
         AND NOTA_ID IN(SELECT Y.NOTA_ID FROM SW_NOTAS Y WHERE Y.APLICABLE=0 AND X.NOTA_ID=Y.NOTA_ID)),0))>0),0)),0)>7 THEN
        (B.TOTAL)-
        NVL(((SELECT SUM(X.IMPORTE) FROM SW_PAGOS X  WHERE X.VENTA_ID=B.VENTA_ID AND X.YEAR>=2007 AND X.FECHA<='14/02/2008' AND X.FORMADEPAGO<>'U')),0) +
        NVL(((SELECT SUM(X.IMPORTE) FROM SW_NOTASDET X  WHERE X.VENTA_ID=B.VENTA_ID AND  X.YEAR>=2007 AND X.SERIE<>'M' AND X.FECHA<='14/02/2008' AND X.ORIGEN='CRE' 
        AND NOTA_ID IN(SELECT Y.NOTA_ID FROM SW_NOTAS Y WHERE Y.APLICABLE=0 AND X.NOTA_ID=Y.NOTA_ID))),0) 
ELSE 0 END)) END,2)||'%' AS PORC
from  SW_VENTAS B
JOIN SW_VENTASCREDITO C ON(C.VENTA_ID=B.VENTA_ID)
JOIN SW_CLIENTES_CREDITO A ON(A.CLIENTE_ID=B.CLIENTE_ID)
WHERE B.YEAR>=2007 AND B.FECHA<='14/02/2008'
AND ((B.TOTAL)-
  NVL ((SELECT SUM(X.IMPORTE) FROM SW_PAGOS X  WHERE X.VENTA_ID=B.VENTA_ID AND X.YEAR>=2007 AND X.FECHA<=TO_DATE('14/02/2008','DD/MM/YYYY')-14 AND X.FORMADEPAGO<>'U'),0) +
   NVL((SELECT SUM(X.IMPORTE) FROM SW_NOTASDET X  WHERE X.VENTA_ID=B.VENTA_ID AND  X.YEAR>=2007 AND X.FECHA<=TO_DATE('14/02/2008','DD/MM/YYYY')-14 AND X.ORIGEN='CRE' 
    AND NOTA_ID IN(SELECT Y.NOTA_ID FROM SW_NOTAS Y WHERE Y.APLICABLE=0 AND X.NOTA_ID=Y.NOTA_ID)),0))>1
GROUP BY 
B.CLAVE,B.NOMBRE
,A.VENDEDOR,A.PLAZO,A.LIMITE
,A.COMENTARIOCXC
ORDER BY STATUS,PORC,SALDO_VENC