SELECT  A.PROVISION_ID,C.CLAVE,C.NOMBRE,C.SUCURSAL,C.NUMERO,TO_CHAR(C.FECHA,'MM/YYYY') AS PERIODO,C.FECHA,A.VENCIMIENTO,A.DIASATRASO
,ROUND((C.SUBTOTAL-C.DEVOLUCIONES),2) AS IMPORTE,A.DESCUENTO1,A.DESCUENTO2,A.CARGOCALCULADO
,ROUND(SUM(B.IMPORTE)*100/(C.SUBTOTAL-C.DEVOLUCIONES),2) AS PORCENTAJE
,ROUND(SUM(B.IMPORTE),2) AS PROVISION
FROM SW_PROVISION A
JOIN SW_PROVISIONDET B ON(A.PROVISION_ID=B.PROVISION_ID)
JOIN V_VENTAS C ON(A.PROVISION_ID=C.VENTA_ID)
WHERE A.APLICADO=0 AND C.SALDO>1 --AND A.PROVISION_ID=2091377
GROUP BY  A.PROVISION_ID,C.CLAVE,C.NOMBRE,C.SUCURSAL,C.NUMERO,TO_CHAR(C.FECHA,'MM/YYYY'),C.FECHA,A.VENCIMIENTO,A.DIASATRASO,C.SUBTOTAL,C.DEVOLUCIONES,A.DESCUENTO1,A.DESCUENTO2,A.CARGOCALCULADO 
ORDER BY C.SUCURSAL
