SELECT B.CLAVE,B.NOMBRE,B.ORIGEN,B.SUCURSAL,B.TIPO,B.NUMERO,B.NUMEROFISCAL,B.FECHA,B.VENCIMIENTO,ROUND(CURRENT_DATE-B.VENCIMIENTO,0) AS DIAS
,B.SALDO
,B.COBRADOR,B.DIAPAGO,B.DIAREVISION
FROM V_VENTAS B
WHERE B.YEAR>2005 AND B.ORIGEN = 'CRE' AND B.SALDO>0 AND ROUND((CURRENT_DATE-1)-B.VENCIMIENTO,0)>0
AND B.CLAVE='U050008'
ORDER BY B.VENCIMIENTO,B.SUCURSAL,B.NUMERO