alter table SW_INVENTARIOM add MOVS number(19,3) default 0 not null

alter table SW_INVENTARIOM add MOVS_COSTO number(19,2) default 0 not null

select 
--SUM(COSTO-(COSTOINI+COSTOCXP+COSTOMAQ+GASTOSMAQ+COMSNA*COSTOP+VENTASN*COSTOP+MOVS_COSTO))
year,mes,CLAVE,COSTOINI,INICIAL,COSTOCXP,CXP ,COSTOMAQ,MAQ,GASTOSMAQ,COMSNA*COSTOP AS COSTO_COMSNA,COMSNA,VENTASN*COSTOP AS COSTO_VTA,VENTASN,MOVS_COSTO,MOVS,COSTO,saldo,COSTOP 
,COSTO-(COSTOINI+COSTOCXP+COSTOMAQ+GASTOSMAQ+COMSNA*COSTOP+VENTASN*COSTOP+MOVS_COSTO) AS DIF
from SW_INVENTARIOM where year=2007 
AND ABS(COSTO-(COSTOINI+COSTOCXP+COSTOMAQ+GASTOSMAQ+COMSNA*COSTOP+VENTASN*COSTOP+MOVS_COSTO))>100