create or replace view V_CLIENTESCRE as
select B.CLIENTE_ID,B.CLAVE,B.NOMBRE
,A.DIA_REVISION,A.DIA_PAGO,A.COBRADOR,A.OPERADOR,A.ORDENDECOMPRA,A.PLAZO,A.TIPO_VENCIMIENTO,A.PAGARE,A.LIMITE,A.LIMITE_MON
,A.COMENTARIOCXC,A.COMENTARIOSVENTAS,A.MODIFICADO,A.RESPALDO,A.CNOTA,A.CORPORATIVO
,SUM(B.IMPORTEBRUTO) AS IMP_BRUTO,SUM(B.IMPMANIOBRAS) AS IMP_MO,SUM(B.IMPCORTES) AS IMP_CORTES,SUM(B.TOTAL) AS TOTAL,SUM(B.KILOS) AS KILOS
,COUNT(B.VENTA_ID) AS FACTS
,COUNT((SELECT X.NUMERO FROM V_VENTAS X WHERE X.VENTA_ID=B.VENTA_ID AND X.VENCIMIENTO<CURRENT_DATE  AND B.SALDO>0)) AS FACTS_VENC
,MAX((SELECT MAX(X.FECHA) FROM V_VENTAS X  WHERE X.VENTA_ID=B.VENTA_ID AND X.FECHA BETWEEN CURRENT_DATE-365 AND CURRENT_DATE)) AS ULTIMAVENTA
,MAX((SELECT MAX(X.FECHA) FROM SW_PAGOS X  WHERE X.VENTA_ID=B.VENTA_ID AND X.FECHA BETWEEN CURRENT_DATE-365 AND CURRENT_DATE)) AS ULTIMOPAGO
,SUM(CASE WHEN B.SERIE='E' THEN B.DESCUENTOS ELSE B.IMPORTEBRUTO*DESCUENTO END) AS DESCUENTOS
,SUM(B.DEVOLUCIONES) AS DEVO,SUM(B.BONIFICACIONES) AS BONIF,SUM(B.DESCUENTO_T) AS DESCTO_T,SUM(B.CARGOS) AS CARGOS,SUM(B.PAGOS) AS PAGOS
,SUM(B.VENTA_NETA) AS VTA_NETA
,SUM(CASE WHEN B.SERIE<>'E' THEN B.VENTA_NETA ELSE 0 END) AS VTA_NETA_CON
,SUM(CASE WHEN B.SERIE='E' THEN B.VENTA_NETA ELSE 0 END) AS VTA_NETA_CRE
,SUM(B.SALDO) AS SALDO
,NVL(SUM((SELECT SUM(X.SALDO) FROM V_VENTAS X WHERE X.VENTA_ID=B.VENTA_ID AND X.VENCIMIENTO<CURRENT_DATE  AND B.SALDO>0)),0) AS SALDO_VENC
,NVL(MAX(ROUND((SELECT (CURRENT_DATE-VENCIMIENTO-1) FROM V_VENTAS X WHERE X.VENTA_ID=B.VENTA_ID AND X.VENCIMIENTO<CURRENT_DATE  AND B.SALDO>0),0)),0) AS ATRASO_MAX
,SUM(B.PROVISION) AS PROV,SUM(B.COSTO) AS COSTO,SUM(B.UTILIDAD) AS UTILIDAD
from  V_VENTAS B
JOIN SW_CLIENTES_CREDITO A ON(A.CLIENTE_ID=B.CLIENTE_ID)
WHERE B.FECHA BETWEEN CURRENT_DATE-365 AND CURRENT_DATE 
GROUP BY B.CLIENTE_ID,B.CLAVE,B.NOMBRE
,A.DIA_REVISION,A.DIA_PAGO,A.COBRADOR,A.OPERADOR,A.ORDENDECOMPRA,A.PLAZO,A.TIPO_VENCIMIENTO,A.PAGARE,A.LIMITE,A.LIMITE_MON
,A.COMENTARIOCXC,A.COMENTARIOSVENTAS,A.MODIFICADO,A.RESPALDO,A.CNOTA,A.CORPORATIVO