CREATE OR REPLACE VIEW V_VENTAS AS
SELECT A.*
,(SELECT NVL(SUM(-B.IMPORTE),0) FROM SW_NOTASDET B WHERE A.VENTA_ID=B.VENTA_ID AND B.TIPO IN('U','V')) AS DESCUENTOS
,(SELECT NVL(SUM(-B.IMPORTE),0) FROM SW_NOTASDET B WHERE A.VENTA_ID=B.VENTA_ID AND B.TIPO IN('H','I','J')) AS DEVOLUCIONES
,(SELECT NVL(SUM(-B.IMPORTE),0) FROM SW_NOTASDET B WHERE A.VENTA_ID=B.VENTA_ID AND B.TIPO IN('F','C','L','Y')) AS BONIFICACIONES
,(SELECT NVL(SUM(-B.IMPORTE),0) FROM SW_NOTASDET B WHERE A.VENTA_ID=B.VENTA_ID AND B.TIPO IN('T')) AS DESCUENTO_T
,(SELECT NVL(SUM(B.IMPORTE),0) FROM SW_NOTASDET B WHERE A.VENTA_ID=B.VENTA_ID AND B.TIPO IN('M','0','P','Q')) AS CARGOS
,(SELECT NVL(SUM(B.IMPORTE),0) FROM SW_PAGOS B WHERE A.VENTA_ID=B.VENTA_ID AND B.FORMADEPAGO NOT IN('K','U')) AS PAGOS
,TOTAL
    -(SELECT NVL(SUM(-B.IMPORTE),0) FROM SW_NOTASDET B WHERE A.VENTA_ID=B.VENTA_ID AND B.TIPO IN('T','U','V','H','I','J','F','C','L','Y','M','0','P','Q')) 
    -(SELECT NVL(SUM(B.PROVISION*1.15),0) FROM SW_PROVISION B WHERE A.VENTA_ID=B.PROVISION_ID AND B.APLICADO=0)
    AS VENTA_NETA 
,(SELECT NVL(SUM(B.PROVISION*1.15),0) FROM SW_PROVISION B WHERE A.VENTA_ID=B.PROVISION_ID AND B.APLICADO=0) AS PROVISION
,TOTAL
-(SELECT NVL(SUM(-B.IMPORTE),0) FROM SW_NOTASDET B WHERE A.VENTA_ID=B.VENTA_ID AND B.TIPO IN('U','V')) 
-(SELECT NVL(SUM(B.IMPORTE),0) FROM SW_PAGOS B WHERE A.VENTA_ID=B.VENTA_ID AND B.FORMADEPAGO NOT IN('K','U')) AS SALDO
,(CASE WHEN ORIGEN IN ('MOS','CAM') THEN 1-(SUBTOTAL-IMPCORTES-IMPMANIOBRAS)/IMPORTEBRUTO --DESCUENTO DE CONTADO
        ELSE (          ---DESCUENTO DE CREDITO
            1-(TOTAL
                -- -(select NVL(SUM(-XX.IMPORTE),0) FROM SW_NOTASDET    xx where xx.TIPO = 'J'  and xx.NOTA_ID in(select yy.NOTAPAGO_ID from SW_PAGOS yy where xx.venta_id=yy.venta_id and yy.REFERENCIA LIKE 'J%')) --DEVOLUCION   NOTAS DE CREDITO POR DEVOLUCION DE ESTA VENTA APLICADAS A LA MISMA (AFECTAN LA UTILIDAD)
                -- -(select NVL(SUM(-XX.IMPORTE),0) FROM SW_NOTASDET    xx where xx.TIPO = 'L'  and xx.NOTA_ID in(select yy.NOTAPAGO_ID from SW_PAGOS yy where xx.venta_id=yy.venta_id and yy.REFERENCIA LIKE 'L%')) --BONIFICACION   NOTAS DE CREDITO POR BONIFICACION (NORMALMENTE DESCUENTOS) DE ESTA VENTA APLICADAS A LA MISMA (AFECTAN LA UTLIDAD)
                ----(SELECT NVL(SUM(-B.IMPORTE),0) FROM SW_NOTASDET B WHERE A.VENTA_ID=B.VENTA_ID AND B.TIPO IN('J'))          --DEVOLUCION
                ---(SELECT NVL(SUM(-B.IMPORTE),0) FROM SW_NOTASDET B WHERE A.VENTA_ID=B.VENTA_ID AND B.TIPO IN('U','V'))          --DESCUENTOS
                -(SELECT NVL(SUM(-B.IMPORTE),0) FROM SW_NOTASDET B WHERE A.VENTA_ID=B.VENTA_ID AND B.TIPO IN('J','L','T','V','U')))/TOTAL)      --DESCUENTO_T
            +(1-(TOTAL-((SELECT NVL(SUM(B.PROVISION*1.15),0) FROM SW_PROVISION B WHERE A.VENTA_ID=B.PROVISION_ID AND B.APLICADO=0)))/TOTAL)  --PROVISION
        END)
 AS DESCUENTO
,(SELECT SUM((-CANTIDAD-
(SELECT NVL(SUM(CANTIDAD),0) FROM SW_DEVODET Z WHERE Z.VENTADET_ID=D.VENTADET_ID AND Z.NOTA_ID IS NOT NULL))
*X.COSTO)*1.15 FROM SW_VENTASDET D JOIN SW_PROMEDIOS X ON( D.ARTICULO_ID=X.ARTICULO_ID AND X.PERIODO=TO_CHAR(D.FECHA,'MM/YYYY'))     
WHERE A.VENTA_ID=D.VENTA_ID) AS COSTO
,TOTAL-(SELECT NVL(SUM(-B.IMPORTE),0) FROM SW_NOTASDET B WHERE A.VENTA_ID=B.VENTA_ID AND B.TIPO IN('T','U','V','H','I','J','F','C','L','Y','M','0','P','Q'))
-(SELECT NVL(SUM(B.PROVISION*1.15),0) FROM SW_PROVISION B WHERE A.VENTA_ID=B.PROVISION_ID AND B.APLICADO=0)
- (SELECT SUM((-CANTIDAD-
(SELECT NVL(SUM(CANTIDAD),0) FROM SW_DEVODET Z WHERE Z.VENTADET_ID=D.VENTADET_ID AND Z.NOTA_ID IS NOT NULL))
*X.COSTO)*1.15 FROM SW_VENTASDET D JOIN SW_PROMEDIOS X ON( D.ARTICULO_ID=X.ARTICULO_ID AND X.PERIODO=TO_CHAR(D.FECHA,'MM/YYYY'))     
WHERE A.VENTA_ID=D.VENTA_ID)
AS UTILIDAD
,(select NVL(SUM(-XX.IMPORTE),0) FROM SW_NOTASDET    xx where XX.VENTA_ID=A.VENTA_ID AND xx.TIPO = 'J'  and xx.NOTA_ID in(select yy.NOTAPAGO_ID from SW_PAGOS yy where xx.venta_id=yy.venta_id and yy.REFERENCIA LIKE 'J%')) AS DEVOLUCION_DESC
,(select NVL(SUM(-XX.IMPORTE),0) FROM SW_NOTASDET    xx where XX.VENTA_ID=A.VENTA_ID AND xx.TIPO = 'L'  and xx.NOTA_ID in(select yy.NOTAPAGO_ID from SW_PAGOS yy where xx.venta_id=yy.venta_id and yy.REFERENCIA LIKE 'L%')) AS BONIFICACION_DESC
,(
    (1+((IMPCORTES+IMPMANIOBRAS)*1.15)/(TOTAL-(((IMPCORTES+IMPMANIOBRAS)*1.15))))
 )
AS FACTOR
FROM SW_VENTAS A where  year>2004